
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-job-
spec:
  entrypoint: job
  volumes:
  - name: shared-volume
    persistentVolumeClaim:
      claimName: job-minio-pv-claim
  templates:
  - name: job-score-test-py
    container:
      image: job:latest
      env:
        - name: DATA_INPUT_PATH
          valueFrom:
            configMapKeyRef:
              name: job-config
              key: data_input_path
        - name: DATA_OUTPUT_PATH
          valueFrom:
            configMapKeyRef:
              name: job-config
              key: data_output_path
      imagePullPolicy: IfNotPresent
      command: ['python', 'src/job/score_test.py']
      volumeMounts:
        - name: shared-volume
          mountPath: /data
  - name: job
    dag:
      tasks:
      - name: job-score-test-py
        template: job-score-test-py