apiVersion: batch/v1
kind: Job
metadata:
  name: job1
spec:
  template:
    spec:
      containers:
      - name: job1
        image: liabifano/scratch-job1:latest
        command: ["python3", "/job1/src/main.py"]
        restartPolicy: Never
      # restartPolicy: OnFailure
  backoffLimit: 10
