apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-
spec:
  entrypoint: job
  templates:
  - name: job-preprocessing
    container:
      image: job
      env:
      - name: DATA_INPUT_PATH
        valueFrom:
          configMapKeyRef:
            name: job-config
            key: data_input_path
      - name: DATA_OUTPUT_PATH
        valueFrom:
          configMapKeyRef:
            name: job-config
            key: data_output_path
      imagePullPolicy: IfNotPresent
      command: ["python3", "src/job/preprocessing.py"]
      volumeMounts:
          - name: shared-volume
            mountPath: /data
