apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      containers:
      - name: {{JOB}}-preprocessing
        image: {{JOB}}
        env:
          - name: DATA_INPUT_PATH
            valueFrom:
              configMapKeyRef:
                name: {{JOB}}-config
                key: data_input_path
          - name: DATA_OUTPUT_PATH
            valueFrom:
              configMapKeyRef:
                name: {{JOB}}-config
                key: data_output_path
        imagePullPolicy: IfNotPresent
        command: ["sleep", "10000"]
        volumeMounts:
          - name: shared-volume
            mountPath: /data
      restartPolicy: Never
      volumes:
        - name: shared-volume
          persistentVolumeClaim:
            claimName: {{JOB}}-minio-pv-claim
