apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{JOB}}-minio
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{JOB}}-minio
    spec:
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{JOB}}-minio-pv-claim
      containers:
      - name: {{JOB}}-minio
        volumeMounts:
        - name: data
          mountPath: "/data"
        image: minio/minio:{{MINIO_RELEASE}}
        args:
        - server
        - /data
        env:
          - name: MINIO_ACCESS_KEY
            value: {{MINIO_ACCESS_KEY}}
          - name: MINIO_SECRET_KEY
            value: {{MINIO_SECRET_KEY}}
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /minio/health/ready
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 20
