apiVersion: v1
kind: Service
metadata:
  name: {{JOB}}-minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: {{JOB}}-minio
